# -*- coding: utf-8 -*-
"""
End-to-end import flow tests.

Test 4 — New customer: verifies that the STD reference is NEVER set by the importer.
Test 8 — Full flow: client → invoice → payment → reconciliation.
"""
from odoo.tests.common import TransactionCase
from odoo.tests import tagged

from ..services.normalizer import (
    NormalizedClient, NormalizedExport, NormalizedInvoice,
    NormalizedInvoiceLine, NormalizedTransaction,
)
from ..services.partner_importer import PartnerImporter
from ..services.import_engine import ImportEngine


@tagged("whmcs", "whmcs_flow")
class TestImportFlow(TransactionCase):

    def setUp(self):
        super().setUp()
        self.config = self.env["whmcs.import.config"].get_config()

        # Activate XAF if needed
        xaf = self.env["res.currency"].search(
            [("name", "=", "XAF"), ("active", "in", [True, False])], limit=1
        )
        if xaf and not xaf.active:
            xaf.active = True

        self.bank_journal = self.env["account.journal"].search(
            [("type", "in", ["bank", "cash"]), ("company_id", "=", self.env.company.id)], limit=1
        )
        if self.bank_journal:
            self.config.default_payment_journal_id = self.bank_journal

    # ------------------------------------------------------------------
    # Test 4 — New customer: importer must NOT set ref
    # The STD reference is generated by Odoo's customization.
    # ------------------------------------------------------------------

    def test_new_partner_ref_never_set_by_importer(self):
        """
        CRITICAL TEST.

        When the importer creates a new partner, it must NEVER include
        'ref' in the vals dict passed to res.partner.create().

        After creation, partner.ref is whatever Odoo's customization
        set it to. We only verify it is not None/empty (i.e. something
        was generated) and that we did not set it manually.
        """
        importer = PartnerImporter(self.env)
        client = NormalizedClient(
            whmcs_id=99001,
            company_name="New Test Company",
            email="newtest@example.cm",
            phone="+237600999001",
            tax_id="M000111222333D",
            country="CM",
        )

        # Verify vals do NOT contain 'ref'
        vals = importer._build_vals(client)
        self.assertNotIn(
            "ref", vals,
            "PartnerImporter._build_vals() must NEVER include 'ref' — "
            "Odoo's customization generates STDxxxxxx automatically."
        )

        # Create and verify
        partner = importer.create_partner(client)
        self.assertTrue(partner.id, "Partner should have been created")

        # Note: in a test database without the STD customization,
        # partner.ref may be empty — that is expected.
        # The important thing is that WE did not set it.
        # In production, it will be STDxxxxxx.
        # We just confirm no exception was raised and partner exists.
        self.assertTrue(partner.exists())

    # ------------------------------------------------------------------
    # Test 8 — Full flow: client → invoice → payment
    # ------------------------------------------------------------------

    def test_full_import_flow(self):
        """
        End-to-end test:
            WHMCS client → Odoo partner
            WHMCS invoice → Odoo account.move (posted)
            WHMCS transaction → Odoo account.payment (posted)
        """
        export = NormalizedExport(
            clients=[
                NormalizedClient(
                    whmcs_id=77001,
                    company_name="Full Flow Test Co",
                    email="fullflow@testco.cm",
                    country="CM",
                )
            ],
            invoices=[
                NormalizedInvoice(
                    whmcs_invoice_id=77001,
                    whmcs_client_id=77001,
                    invoice_number="INV-FF-77001",
                    date="2026-08-01",
                    due_date="2026-08-15",
                    currency="XAF",
                    status="Paid",
                    total=100000,
                    lines=[
                        NormalizedInvoiceLine(
                            description="Full Flow Service",
                            quantity=1,
                            unit_price=100000,
                        )
                    ],
                )
            ],
            transactions=[
                NormalizedTransaction(
                    whmcs_transaction_id=77001,
                    transaction_reference="TXN-FF-77001",
                    whmcs_invoice_id=77001,
                    whmcs_client_id=77001,
                    date="2026-08-05",
                    amount=100000,
                    currency="XAF",
                    gateway="manual",
                )
            ],
        )

        batch = self.env["whmcs.import.batch"].create({
            "name": "Full Flow Test",
            "mode": "import",
            "state": "running",
        })

        engine = ImportEngine(self.env, batch, self.config, dry_run=False)
        summary = engine.run(export)

        # 1 partner created
        self.assertEqual(summary["created_clients"], 1)
        partner = self.env["res.partner"].search([("email", "=", "fullflow@testco.cm")])
        self.assertEqual(len(partner), 1, "Exactly one partner must be created")

        # 1 invoice created and posted
        self.assertEqual(summary["created_invoices"], 1)
        mapping = self.env["whmcs.invoice.mapping"].search(
            [("whmcs_invoice_id", "=", 77001)]
        )
        self.assertTrue(mapping, "Invoice mapping must be created")
        invoice = mapping.invoice_id
        self.assertEqual(invoice.state, "posted", "Invoice must be posted")
        self.assertEqual(invoice.partner_id.id, partner.id)

        # 1 payment created and posted
        self.assertEqual(summary["created_transactions"], 1)
        txn_mapping = self.env["whmcs.transaction.mapping"].search(
            [("whmcs_transaction_id", "=", 77001)]
        )
        self.assertTrue(txn_mapping, "Transaction mapping must be created")
        payment = txn_mapping.payment_id
        self.assertEqual(payment.state, "posted", "Payment must be posted")
        self.assertEqual(payment.partner_id.id, partner.id)

    # ------------------------------------------------------------------
    # Test: Dry run creates nothing
    # ------------------------------------------------------------------

    def test_dry_run_creates_nothing(self):
        """In dry run mode, no Odoo records should be created."""
        export = NormalizedExport(
            clients=[
                NormalizedClient(
                    whmcs_id=66001,
                    company_name="Dry Run Test Co",
                    email="dryrun@nowhere.cm",
                )
            ],
            invoices=[
                NormalizedInvoice(
                    whmcs_invoice_id=66001,
                    whmcs_client_id=66001,
                    invoice_number="INV-DR-66001",
                    date="2026-08-01",
                    due_date="2026-08-15",
                    currency="XAF",
                    status="Paid",
                    total=50000,
                )
            ],
            transactions=[],
        )

        batch = self.env["whmcs.import.batch"].create({
            "name": "Dry Run Test",
            "mode": "dry_run",
            "state": "analyzing",
        })
        engine = ImportEngine(self.env, batch, self.config, dry_run=True)
        engine.run(export)

        # No partner created
        partner = self.env["res.partner"].search([("email", "=", "dryrun@nowhere.cm")])
        self.assertFalse(partner, "Dry run must not create any partners")

        # No invoice mapping created
        mapping = self.env["whmcs.invoice.mapping"].search(
            [("whmcs_invoice_id", "=", 66001)]
        )
        self.assertFalse(mapping, "Dry run must not create invoice mappings")

    # ------------------------------------------------------------------
    # Test: Error in one record does not block others
    # ------------------------------------------------------------------

    def test_error_does_not_block_batch(self):
        """
        One bad invoice (missing currency) must not prevent
        subsequent valid invoices from being imported.
        """
        export = NormalizedExport(
            clients=[
                NormalizedClient(whmcs_id=55001, company_name="Error Test Co A", email="errora@test.cm"),
                NormalizedClient(whmcs_id=55002, company_name="Error Test Co B", email="errorb@test.cm"),
            ],
            invoices=[
                # Bad invoice — unknown currency
                NormalizedInvoice(
                    whmcs_invoice_id=55001,
                    whmcs_client_id=55001,
                    invoice_number="INV-ERR-55001",
                    date="2026-08-01",
                    currency="NONEXISTENT_CURRENCY",
                    status="Paid",
                    total=10000,
                ),
                # Good invoice
                NormalizedInvoice(
                    whmcs_invoice_id=55002,
                    whmcs_client_id=55002,
                    invoice_number="INV-ERR-55002",
                    date="2026-08-01",
                    currency="XAF",
                    status="Unpaid",
                    total=20000,
                    lines=[NormalizedInvoiceLine(description="OK Service", quantity=1, unit_price=20000)],
                ),
            ],
            transactions=[],
        )

        batch = self.env["whmcs.import.batch"].create({
            "name": "Error Isolation Test",
            "mode": "import",
            "state": "running",
        })
        engine = ImportEngine(self.env, batch, self.config, dry_run=False)
        summary = engine.run(export)

        # The good invoice must still be imported
        good_mapping = self.env["whmcs.invoice.mapping"].search(
            [("whmcs_invoice_id", "=", 55002)]
        )
        self.assertTrue(good_mapping, "Good invoice must be imported despite error in previous invoice")

        # Error count should be at least 1
        self.assertGreaterEqual(summary["error_count"], 1)
