# -*- coding: utf-8 -*-
"""
Partner Importer.

Creates new res.partner records from NormalizedClient objects.

CRITICAL RULE:
    This module NEVER sets the `ref` field.
    The company's Odoo customization generates STDxxxxxx automatically
    when res.partner.create() is called.
    Do not reproduce or guess that logic here.
"""
import logging

from .normalizer import NormalizedClient

_logger = logging.getLogger(__name__)


class PartnerImporter:

    def __init__(self, env):
        self.env = env

    def create_partner(self, client: NormalizedClient) -> "res.partner":
        """
        Create a new Odoo partner from a NormalizedClient.

        Deliberately does NOT set `ref`.
        After creation, partner.ref will contain the auto-generated STDxxxxxx.
        """
        vals = self._build_vals(client)
        _logger.info(
            "Creating Odoo partner for WHMCS client %s: %s",
            client.whmcs_id,
            client.display_name,
        )
        partner = self.env["res.partner"].create(vals)
        _logger.info(
            "Created partner id=%s ref=%s for WHMCS client %s",
            partner.id,
            partner.ref,
            client.whmcs_id,
        )
        return partner

    def create_partners_batch(self, clients):
        """Create multiple partners with one ORM create call.
        Returns records in the same order as ``clients``.
        """
        vals_list = [self._build_vals(client) for client in clients]
        if not vals_list:
            return self.env["res.partner"]
        _logger.info("Creating partner batch of %s records", len(vals_list))
        partners = self.env["res.partner"].create(vals_list)
        _logger.info("Created partner batch: %s records", len(partners))
        return partners

    def _build_vals(self, client: NormalizedClient) -> dict:
        """Build the vals dict for res.partner.create() — never includes ref."""
        vals = {}

        # Name: company takes precedence; fall back to full name
        if client.company_name:
            vals["name"] = client.company_name
            vals["is_company"] = True
        else:
            full_name = " ".join(
                p for p in [client.first_name, client.last_name] if p
            ).strip()
            vals["name"] = full_name or f"WHMCS Client #{client.whmcs_id}"
            vals["is_company"] = False

        # Contact details
        if client.email:
            vals["email"] = client.email.strip().lower()
        if client.phone:
            vals["phone"] = client.phone.strip()
        # Odoo 19 no longer provides the standard res.partner.mobile field.
        # Only write it when a custom module has explicitly added it; otherwise
        # keep the WHMCS number in the native phone field.
        if client.mobile and "mobile" in self.env["res.partner"]._fields:
            vals["mobile"] = client.mobile.strip()
        elif client.mobile and not client.phone:
            vals["phone"] = client.mobile.strip()

        # Address
        if client.address1:
            vals["street"] = client.address1
        if client.address2:
            vals["street2"] = client.address2
        if client.city:
            vals["city"] = client.city
        if client.postcode:
            vals["zip"] = client.postcode

        # Country — look up res.country by ISO code
        if client.country:
            country = self.env["res.country"].search(
                [("code", "=", client.country.upper())], limit=1
            )
            if country:
                vals["country_id"] = country.id
            else:
                _logger.warning(
                    "Unknown country code '%s' for WHMCS client %s",
                    client.country, client.whmcs_id,
                )

        # VAT / tax ID
        if client.tax_id:
            vals["vat"] = client.tax_id.strip()

        # Microsoft ID — only when the Odoo database exposes the Studio/custom
        # field. Keeping this in the canonical import prevents a newly-created
        # partner from losing one of the identifiers used by the resolver.
        if client.microsoft_id and "x_studio_microsoft_id" in self.env["res.partner"]._fields:
            vals["x_studio_microsoft_id"] = client.microsoft_id.strip()

        # Language
        if client.language:
            # Map WHMCS language codes to Odoo lang codes if possible
            lang_map = {
                "french": "fr_FR",
                "english": "en_US",
                "fr": "fr_FR",
                "en": "en_US",
            }
            lang_code = lang_map.get(client.language.lower(), client.language)
            lang = self.env["res.lang"].search([("code", "=", lang_code)], limit=1)
            if lang:
                vals["lang"] = lang_code

        # Customer / supplier flags
        vals["customer_rank"] = 1

        # NOTE: We deliberately do NOT set vals["ref"]
        # The STDxxxxxx reference is generated by the company's Odoo customization.

        return vals
